config/routes.rb
Rails.application.routes.draw do
  resources :products

  resources :bills

  resources :fixed_assets

  resources :balance_sheets

  resources :employees

  resources :vendors

  resources :customers

  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contact'

  root 'static_pages#index'

  match "/pay/:id" => "employees#pay", as:"pay" ,:via => [:get, :post]
  match "/bill/pay/:id" => "bills#pay", as:"pay_bill" ,:via => [:get, :post]

  match "/payroll" => 'employees#payroll', as:"payroll",:via => [:get, :post]

  match "/incomestatement" => 'balance_sheets#incomestatement', as:"income",:via => [:get, :post]

  match "/buy/:id" => "products#buy", as:"buy", :via => [:get, :post]
  match "/sell/:id" => "products#sell", as:"sell", :via => [:get, :post]

  match "/purchase/:id" => "products#purchase", as:"purchase", :via => [:get, :post]  # The priority is based upon order of creation: first created -> highest priority.
  match "/hawk/:id" => "products#hawk", as:"hawk", :via => [:get, :post]

  match "/pay_tax" => "static_pages#pay_tax", as:"pay_tax", :via => [:get, :post]

end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_path, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def pay
    @employee = Employee.find(params[:id])
    pay = @employee.salary
    @paid_date = Time.now
    @employee.pay_date = @paid_date
    $payroll = $payroll + (0.75 * pay)
    puts pay
    puts $cash
    $cash = $cash - pay
    $withholding = $withholding + (0.25 * pay)
    puts $cash
    puts @employee.pay_date
    @employee.save
    redirect_to "/balance_sheets"
  end

  def payroll
    @employees = Employee.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:firstname, :lastname, :address1, :address2, :city, :state, :zipcode, :ssn, :withholding, :salary, :pay_date)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname, 'First Name' %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname, 'Last Name' %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :address1, 'Address Line 1' %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2, 'Address Line 2' %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zipcode, 'Zip Code' %><br>
    <%= f.number_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :ssn, 'Social Security Number' %><br>
    <%= f.text_field :ssn %>
  </div>
  <div class="field">
    <%= f.label :withholding, 'Number of Withholdings' %><br>
    <%= f.number_field :withholding %>
  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.text_field :salary %>
  </div>
  <button class="btn btn-lg btn-default">
      <%= f.submit %>
  </button>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
 <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Nectar Chicken Company</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/grayscale.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

 <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href='./'>
                    <i class="fa fa-play-circle"></i>  <span class="light">Nectar</span> Chicken Co.
                </a>
            </div>


            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

<header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">

                      <h1>Listing employees</h1>

                      <table class = 'table'>
                        <thead>
                          <tr>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Address Line 1</th>
                            <th>Address Line 2</th>
                            <th>City</th>
                            <th>State</th>
                            <th>Zip Code</th>
                            <th>SSN</th>
                            <th>No. of Withholding</th>
                            <th>Salary</th>
                            <th colspan="3"></th>
                          </tr>
                        </thead>

                        <tbody>
                          <% @employees.each do |employee| %>
                            <tr>
                              <td><%= employee.firstname %></td>
                              <td><%= employee.lastname %></td>
                              <td><%= employee.address1 %></td>
                              <td><%= employee.address2 %></td>
                              <td><%= employee.city %></td>
                              <td><%= employee.state %></td>
                              <td><%= employee.zipcode %></td>
                              <td><%= employee.ssn %></td>
                              <td><%= employee.withholding %></td>
                              <td><%= employee.salary %></td>
                              <td><button><%= link_to 'Pay', pay_path(employee) %></button></td>
                            </tr>
                          <% end %>
                        </tbody>
                      </table>

                      <br>

                      <button class="btn btn-lg btn-default"><%= link_to 'New Employee', new_employee_path %></button>
                    </div>
                </div>
            </div>
        </div>
    </header>


    <!-- jQuery Version 1.11.0 -->
    <script src="js/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="js/jquery.easing.min.js"></script>


    <!-- Custom Theme JavaScript -->
    <script src="js/grayscale.js"></script>

</body>

app/views/employees/new.html.erb
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Nectar Chicken Company</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/grayscale.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="../">
                    <i class="fa fa-play-circle"></i>  <span class="light">Nectar</span> Chicken Co.
                </a>
            </div>


        </div>
        <!-- /.container -->
    </nav>
    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">

						<h4>New employee</h4>

						<%= render 'form' %>
					            </div>
        </div>
    </section>

</body>

app/views/employees/payroll.html.erb
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Nectar Chicken Company</title>

  <!-- Bootstrap Core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/grayscale.css" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
        <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand page-scroll" href='./'>
        <i class="fa fa-play-circle"></i>  <span class="light">Nectar</span> Chicken Co.
      </a>
    </div>


    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

<header class="intro">
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">

          <h1>Payroll</h1>

          <table class = 'table'>
            <thead>
            <tr>
              <th>Date</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Amount Paid</th>
              <th>Withholding</th>
              <th>Salary</th>
              <th colspan="3"></th>
            </tr>
            </thead>

            <tbody>
            <% @employees.each do |employee| %>
                <tr>
                  <td><%= employee.pay_date%></td>
                  <td><%= employee.firstname %></td>
                  <td><%= employee.lastname %></td>
                  <td><%= 0.75 * employee.salary %></td>
                  <td><%= 0.25 * employee.salary %></td>
                  <td><%= employee.salary %></td>
                </tr>
            <% end %>
            </tbody>


          </table>

          <br>
        </div>
      </div>
    </div>
  </div>
</header>


<!-- jQuery Version 1.11.0 -->
<script src="js/jquery-1.11.0.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

<!-- Plugin JavaScript -->
<script src="js/jquery.easing.min.js"></script>


<!-- Custom Theme JavaScript -->
<script src="js/grayscale.js"></script>

</body>

app/views/employees/show.html.erb
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Nectar Chicken Company</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/grayscale.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="../">
                    <i class="fa fa-play-circle"></i>  <span class="light">Nectar</span> Chicken Co.
                </a>
            </div>


        </div>

    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">    
                        <p id="notice"><%= notice %></p>

                        <p>
                          <strong>First Name:</strong>
                          <%= @employee.firstname %>
                        </p>

                        <p>
                          <strong>Last Name:</strong>
                          <%= @employee.lastname %>
                        </p>

                        <p>
                          <strong>Address Line 1:</strong>
                          <%= @employee.address1 %>
                        </p>

                        <p>
                          <strong>Address Line 2:</strong>
                          <%= @employee.address2 %>
                        </p>

                        <p>
                          <strong>City:</strong>
                          <%= @employee.city %>
                        </p>

                        <p>
                          <strong>State:</strong>
                          <%= @employee.state %>
                        </p>

                        <p>
                          <strong>Zip Code:</strong>
                          <%= @employee.zipcode %>
                        </p>

                        <p>
                          <strong>Social Security Number:</strong>
                          <%= @employee.ssn %>
                        </p>

                        <p>
                          <strong>Number of Withholding:</strong>
                          <%= @employee.withholding %>
                        </p>

                        <p>
                          <strong>Salary:</strong>
                          <%= @employee.salary %>
                        </p>

                        <button class="btn btn-lg btn-default"><%= link_to 'Edit', edit_employee_path(@employee) %></button> 
                          </div>
                </div>
            </div>
        </div>
    </header>