config/routes.rb
Rails.application.routes.draw do
  resources :products

  resources :bills

  resources :fixed_assets

  resources :balance_sheets

  resources :employees

  resources :vendors

  resources :customers

  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contact'

  root 'static_pages#index'

  match "/pay/:id" => "employees#pay", as:"pay" ,:via => [:get, :post]
  match "/bill/pay/:id" => "bills#pay", as:"pay_bill" ,:via => [:get, :post]

  match "/payroll" => 'employees#payroll', as:"payroll",:via => [:get, :post]

  match "/incomestatement" => 'balance_sheets#incomestatement', as:"income",:via => [:get, :post]

  match "/buy/:id" => "products#buy", as:"buy", :via => [:get, :post]
  match "/sell/:id" => "products#sell", as:"sell", :via => [:get, :post]

  match "/purchase/:id" => "products#purchase", as:"purchase", :via => [:get, :post]  # The priority is based upon order of creation: first created -> highest priority.
  match "/hawk/:id" => "products#hawk", as:"hawk", :via => [:get, :post]

  match "/pay_tax" => "static_pages#pay_tax", as:"pay_tax", :via => [:get, :post]

end

app/models/bill.rb
class Bill < ActiveRecord::Base
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to bills_path, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def pay
    @bill = Bill.find(params[:id])
    pay = @bill.amount
    $bills = $bills + pay
    $cash = $cash - pay
    redirect_to "/balance_sheets"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:name, :amount)
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Nectar Chicken Company</title>

  <!-- Bootstrap Core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/grayscale.css" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
        <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand page-scroll" href='./'>
        <i class="fa fa-play-circle"></i>  <span class="light">Nectar</span> Chicken Co.
      </a>
    </div>


    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

<header class="intro">
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">

          <h1>Listing Bills</h1>

          <table class = 'table'>
            <thead>
            <tr>
              <th>Type</th>
              <th>Amount</th>
            </thead>

            <tbody>
            <% @bills.each do |bill| %>
                <tr>
                  <td><%= bill.name %></td>
                  <td><%= bill.amount %></td>
                  <td><button><%= link_to 'Pay', pay_bill_path(bill) %></button></td>
                </tr>
            <% end %>
            </tbody>
          </table>

          <br>

          <button class="btn btn-lg btn-default"><%= link_to 'Add a Bill', new_bill_path %></button>
        </div>
      </div>
    </div>
  </div>
</header>


<!-- jQuery Version 1.11.0 -->
<script src="js/jquery-1.11.0.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

<!-- Plugin JavaScript -->
<script src="js/jquery.easing.min.js"></script>


<!-- Custom Theme JavaScript -->
<script src="js/grayscale.js"></script>

</body>

app/views/bills/new.html.erb
<h1>New bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @bill.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @bill.amount %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>