config/routes.rb
Rails.application.routes.draw do
  resources :products

  resources :bills

  resources :fixed_assets

  resources :balance_sheets

  resources :employees

  resources :vendors

  resources :customers

  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contact'

  root 'static_pages#index'

  match "/pay/:id" => "employees#pay", as:"pay" ,:via => [:get, :post]
  match "/bill/pay/:id" => "bills#pay", as:"pay_bill" ,:via => [:get, :post]

  match "/payroll" => 'employees#payroll', as:"payroll",:via => [:get, :post]

  match "/incomestatement" => 'balance_sheets#incomestatement', as:"income",:via => [:get, :post]

  match "/buy/:id" => "products#buy", as:"buy", :via => [:get, :post]
  match "/sell/:id" => "products#sell", as:"sell", :via => [:get, :post]

  match "/purchase/:id" => "products#purchase", as:"purchase", :via => [:get, :post]  # The priority is based upon order of creation: first created -> highest priority.
  match "/hawk/:id" => "products#hawk", as:"hawk", :via => [:get, :post]

  match "/pay_tax" => "static_pages#pay_tax", as:"pay_tax", :via => [:get, :post]

end

app/models/product.rb
class Product < ActiveRecord::Base
  #has_and_belongs_to_many :vendors
  #has_and_belongs_to_many :customers
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all

  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        if params[:type] == "buy"
          format.html { redirect_to purchase_path, notice: 'Product was successfully bought.' }
          format.json { render :show, status: :ok, location: @product }
        elsif params[:type] == "sell"
          format.html { redirect_to hawk_path, notice: 'Product was successfully sold.' }
          format.json { render :show, status: :ok, location: @product }
        end
      else

        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def buy
    @product = Product.find(params[:id])
    #@vendor = Vendor.find(@product.vendor_id)
  end

  def purchase
    @product = Product.find(params[:id])
    $cash = $cash - @product.amt_paid
    $payable = $payable + @product.amt_debt
    @product.quantity = @product.quantity + @product.buy_quantity
    @product.save
    $inventory_total = $inventory_total + (@product.buy_quantity * @product.costprice)
    puts $inventory_total
    puts $cash
    redirect_to "/balance_sheets"
  end

  def sell
    @product = Product.find(params[:id])

  end

  def hawk
    @product = Product.find(params[:id])
    #@customer = Customer.find(@product.customer_id)
    $cash = $cash + @product.amt_sold
    $receivable = $receivable + @product.amt_loaned
    @product.quantity = @product.quantity - @product.sell_quantity
    @product.save
    $inventory_total = $inventory_total - (@product.sell_quantity * @product.costprice)
    $cogs = $cogs + (@product.sell_quantity * @product.costprice)
    $sales = $sales + (@product.sell_quantity * @product.sellprice)
    redirect_to "/balance_sheets"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :costprice, :sellprice, :vendor_id, :customer_id, :quantity, :amt_paid, :amt_debt, :amt_sold, :amt_loaned, :buy_quantity, :sell_quantity, :type)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :costprice %><br>
    <%= f.text_field :costprice %>
  </div>
  <div class="field">
    <%= f.label :sellprice %><br>
    <%= f.text_field :sellprice %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/buy.html.erb
<h1>Purchase Order</h1>

<%= form_for(@product) do |f| %>
    <input type="hidden" name="type" value="buy">
    <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% @product.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>Quantity in Stock= <%= @product.quantity%></p>
    <div class="field">
      <%= f.label :buy_quantity %><br>
      <%= f.text_field :buy_quantity %>
    </div>
    <p>Cost Price= <%= @product.costprice%></p>
    <div class="field">
      <%= f.label :amt_paid %><br>
      <%= f.text_field :amt_paid %>
    </div>
    <div class="field">
      <%= f.label :amt_debt %><br>
      <%= f.text_field :amt_debt %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Inventory</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cost Price per unit</th>
      <th>Sell Price per unit</th>
      <th>Quantity</th>
      <th>Value</th>
      <th>Re-Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.costprice %></td>
        <td><%= product.sellprice %></td>
        <td><%= product.quantity %></td>
        <td><%= product.costprice * product.quantity %></td>
        <% if (product.quantity < 50 )%>
            <td>yes</td>
        <% else%>
            <td></td>
        <% end %>
        <td><button><%= link_to 'Buy', buy_path(product) %></button></td>
        <td><button><%= link_to 'Sell', sell_path(product) %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/sell.html.erb
<h1>Invoice</h1>

<%= form_for(@product) do |f| %>
    <input type="hidden" name="type" value="sell">
    <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% @product.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>Quantity in Stock= <%= @product.quantity%></p>
    <div class="field">
      <%= f.label :sell_quantity %><br>
      <%= f.text_field :sell_quantity %>
    </div>
    <p>Sell Price= <%= @product.sellprice%></p>
    <div class="field">
      <%= f.label :amt_sold %><br>
      <%= f.text_field :amt_sold %>
    </div>
    <div class="field">
      <%= f.label :amt_loaned %><br>
      <%= f.text_field :amt_loaned %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Costprice:</strong>
  <%= @product.costprice %>
</p>

<p>
  <strong>Sellprice:</strong>
  <%= @product.sellprice %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @product.vendor_id %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @product.customer_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>